'''
More info on these config values can be found here:
https://flask.palletsprojects.com/en/2.0.x/config/
'''

# ENV='development'
# DEBUG=True
# TESTING=False
# PROPAGATE_EXCEPTIONS=None
# PRESERVE_CONTEXT_ON_EXCEPTION=None
# TRAP_HTTP_EXCEPTIONS=False
# TRAP_BAD_REQUEST_ERRORS=None
# SECRET_KEY='raplace_me_with_random_string'
# SESSION_COOKIE_NAME='session'
# SESSION_COOKIE_DOMAIN=None
# SESSION_COOKIE_PATH=None
# SESSION_COOKIE_HTTPONLY=True
# SESSION_COOKIE_SECURE=False
# SESSION_COOKIE_SAMESITE=None
# PERMANENT_SESSION_LIFETIME=2678400
# SESSION_REFRESH_EACH_REQUEST=True
# USE_X_SENDFILE=False
# SEND_FILE_MAX_AGE_DEFAULT=None
# SERVER_NAME=None
# APPLICATION_ROOT='/'
# PREFERRED_URL_SCHEME='http'
# MAX_CONTENT_LENGTH=None
# JSON_AS_ASCII=True
# JSON_SORT_KEYS=True
# JSONIFY_PRETTYPRINT_REGULAR=False
# JSONIFY_MIMETYPE='application/json'
# TEMPLATES_AUTO_RELOAD=None
# EXPLAIN_TEMPLATE_LOADING=False
# MAX_COOKIE_SIZE=4093

'''
Configure whatever other variables you want here
'''

# For Example
# DATABASE='hostname:port'